" vim:set foldmethod=marker:

" let VIMFILES variable be vim root directory

" if on windows platform
if has('win32') || has('win64')
  let $VIMFILES = expand('~').'/dotfiles/vim'
elseif has('unix') || has('mac')
  let $VIMFILES = expand('~').'/.vim'
end

" source original vimrc
if filereadable(expand($VIMFILES."/setup/vimrc.vim"))
  source $VIMFILES/setup/vimrc.vim
endif

if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif

