" vim:set foldmethod=marker:

" let VIMFILES variable be vim root directory

" if on windows platform
if has('win32') || has('win64')
  let $VIMFILES = expand('~').'/dotfiles/vim'
elseif has('unix') || has('mac')
  let $VIMFILES = expand('~').'/.vim'
end

" Change cursor shape between insert and normal mode in iTerm2.app
if $TERM_PROGRAM =~ "iTerm"
    let &t_EI = "\<Esc>]50;CursorShape=0\x7" " Block in normal mode
    let &t_SI = "\<Esc>]50;CursorShape=1\x7" " Vertical bar in insert mode
    let &t_SR = "\<Esc>]50;CursorShape=2\x7" " Underline in replace mode
endif

" source original vimrc
if filereadable(expand($VIMFILES."/setup/vimrc.vim"))
  source $VIMFILES/setup/vimrc.vim
endif

if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif

